---
- hosts: raspberrypi
  become: yes

  vars_files:
    - ./vars.yml  

  pre_tasks:  
    - apt: update_cache=yes cache_valid_time=3600

    - name: Ensure user
      user:
        name: "{{ username }}"
        groups: "{{ user_groups }}"
        password: "{{ user_password }}"
        update_password: on_create
        append: true
      register: user_details

  roles:
    - role: users
      tags: [users]
    
    - role: ntp
      tags: [ntp]

    - role: minidlna
      tags: [minidlna]

    - role: samba
      tags: [samba]

    - role: pihole
      tags: [pihole]

    - role: docker
      tags: [docker]

    - role: docker-smokeping
      tags: [docker-smokeping]
