---
- name: Install
  apt: name=minidlna state=present

- name: Ensure user
  user: name=minidlna create_home=no

- name: Execute with correct user
  lineinfile:
    path: /etc/minidlna.conf
    regexp: '^#?user='
    line: 'user=minidlna'

- name: Share desired directories
  notify: Restart minidlna
  blockinfile:
    path: /etc/minidlna.conf
    insertafter: '^#.*"PV" for pictures and video'
    block: "{{ minidlna_shares }}"
