---
- name: Ensure dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-pip

- name: Ensure gpg key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_lsb.id | lower }}/gpg"
    state: present

- name: Ensure repo
  apt_repository:
    repo: >-
      deb [arch={{ docker_package_architecture }}]
      https://download.docker.com/linux/{{ ansible_lsb.id | lower }} {{ ansible_lsb.codename }} stable
    state: present
    update_cache: yes

- name: Ensure install
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Ensure docker can be ran without root
  user:
    name: "{{ user_details.name }}"
    append: yes
    groups: docker


- name: Ensure ansible dependencies
  pip: name=docker executable=pip3
